# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairoa" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_darwin_x86_64.tar.gz"
      sha256 "d00fd05502c7e4fe0abb692845d6c76f1694dc2bd69685807d5234893ce6f193"
    end
    on_arm do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "ada8cf93bbbd119a731ee32ba8db9b3faa9115ea10134cc32946f6e3aefbe5fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_linux_x86_64.tar.gz"
      sha256 "adc7ff1b6ebadc0a613cc1fb8fd0bff067eced88373fc0e4f2051c1ddd6b995f"
    end
    on_arm do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_linux_arm64.tar.gz"
      sha256 "6f53f8fd9b7a335d9ea5105d03ada13a5219b91183d60d5f1b609b55d2c77e2e"
    end
  end

  name "kairoa"
  desc "Kairoa CLI - A developer toolbox with 50+ utilities"
  homepage "https://github.com/covoyage/kairoa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairoa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kairoa"]
    end
  end

  # No zap stanza required

end
