# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairoa" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_darwin_x86_64.tar.gz"
      sha256 "68024cc48b8175d18f57779e3bd09f8bc633be1f471adefcdd0089876151e2ea"
    end
    on_arm do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "99802fc888b1614a4cc07831c7b5af0b2bf5edcd9083a40fd4f4f6945429283a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_linux_x86_64.tar.gz"
      sha256 "588e93de13b3a709fdccb2ac9ebfe83498d0fed6cbff6f493c74b6d783f72f51"
    end
    on_arm do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_linux_arm64.tar.gz"
      sha256 "f66f5bb19eeb2a298afe4ecad7bcabe56159c4458de25676bd49f1c29f2b348a"
    end
  end

  name "kairoa"
  desc "Kairoa CLI - A developer toolbox with 50+ utilities"
  homepage "https://github.com/covoyage/kairoa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairoa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kairoa"]
    end
  end

  # No zap stanza required

end
