# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairoa" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_darwin_x86_64.tar.gz"
      sha256 "6de8c7f701cb8f16771ef93312bc0064d4842cb2722acf57482d12618b366814"
    end
    on_arm do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "55c00b85578cdbbe5ff61048624398bcd8226939ebc09200b569e08e589eecc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_linux_x86_64.tar.gz"
      sha256 "ffbce4d94b66970f6776e90f1f98cd9e301f1bf3e805529e00179a139d01a741"
    end
    on_arm do
      url "https://github.com/covoyage/kairoa-cli/releases/download/v#{version}/kairoa-cli_#{version}_linux_arm64.tar.gz"
      sha256 "30d84781a0d0ecdf6508145af1eb366d6b667e226e1fa70ee31f447f49111613"
    end
  end

  name "kairoa"
  desc "Kairoa CLI - A developer toolbox with 50+ utilities"
  homepage "https://github.com/covoyage/kairoa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairoa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kairoa"]
    end
  end

  # No zap stanza required

end
